// Tool descriptions (G.REQLIX_GET_I.1, G.REQLIX_GET_CA.1, G.REQLIX_GET_CH.1, G.REQLIX_GET_REQUIREMENTS.1, G.REQLIX_GET_REQUIREMENT.1, G.REQLIX_I.1, G.REQLIX_U.1)

pub(crate) const GET_INSTRUCTIONS_DESC: &str = "CALL THIS BEFORE ANY CODE OPERATION (reading or writing). \
Returns instructions on how to work with requirements. \
This MCP server is the single source of truth for everything related to requirements. \
Returns JSON with \"success\": true and \"data\": {\"content\": \"...\"} containing instructions and categories list. \
On error, returns JSON with \"success\": false and \"error\": \"error message\".";

pub(crate) const GET_CATEGORIES_DESC: &str =
    "Returns a list of all available requirement categories. \
Use this to discover what categories exist before querying chapters or requirements. \
Returns JSON with \"success\": true and \"data\": {\"categories\": [...]} (alphabetically sorted). \
If no categories exist, returns empty array: \"categories\": []. \
On error, returns JSON with \"success\": false and \"error\": \"error message\".";

pub(crate) const GET_CHAPTERS_DESC: &str = "Returns a list of all chapters (level-1 headings) in the \
specified category file. Use this to discover what chapters exist in a category before querying requirements. \
Returns JSON with \"success\": true and \"data\": {\"category\": \"...\", \"chapters\": [...]}. \
If category has no chapters, returns empty array: \"chapters\": []. \
On error (category not found), returns JSON with \"success\": false and \"error\": \"error message\".";

pub(crate) const GET_REQUIREMENTS_DESC: &str = "Returns a list of all requirement titles (with indices) \
in the specified category and chapter. Use this to browse requirements in a chapter. \
To get full requirement content, use reqlix_get_requirement. \
Returns JSON with \"success\": true and \"data\": {\"category\": \"...\", \"chapter\": \"...\", \"requirements\": [{\"index\": \"...\", \"title\": \"...\"}, ...]}. \
If chapter has no requirements, returns empty array: \"requirements\": []. \
On error (category/chapter not found), returns JSON with \"success\": false and \"error\": \"error message\".";

// G.REQLIX_GET_REQUIREMENT.1
pub(crate) const GET_REQUIREMENT_DESC: &str = "Returns the full content (title and text) of one or more requirements by index. \
Index format: {CATEGORY}.{CHAPTER}.{NUMBER} (e.g., G.G.1, T.U.2). \
Supports batch requests with up to 100 indices. \
Single request: Returns JSON with \"success\": true and \"data\": {...}. On error, returns \"success\": false. \
Batch request: Returns \"success\": true and \"data\": [{...}, ...]. Each element has its own \"success\" and \"data\" or \"error\" field.";

pub(crate) const INSERT_REQUIREMENT_DESC: &str = "Inserts a new requirement into the specified category \
and chapter. The title must be generated by the LLM and provided as a parameter. \
The title must be a concise name that reflects the essence of the requirement. \
Category must contain only lowercase English letters (a-z) and underscore (_). \
Chapter must contain only uppercase and lowercase English letters (A-Z, a-z), spaces, colons (:), and hyphens (-). \
Returns JSON with \"success\": true and \"data\": {\"index\": \"...\", \"title\": \"...\", \"text\": \"...\", \"category\": \"...\", \"chapter\": \"...\"}. \
On error (title already exists, file system error, validation error), returns JSON with \"success\": false and \"error\": \"error message\".";

// G.REQLIX_U.1
pub(crate) const UPDATE_REQUIREMENT_DESC: &str = "Updates one or more existing requirements by index with new text and optional new title. \
If title is provided, it must be unique within the chapter. If not provided, the existing title is kept. \
Supports batch updates with up to 100 requirements. \
Category must contain only lowercase English letters (a-z) and underscore (_). \
Chapter must contain only uppercase and lowercase English letters (A-Z, a-z), spaces, colons (:), and hyphens (-). \
Single update: Returns JSON with \"success\": true and \"data\": {...}. On error, returns \"success\": false. \
Batch update: Returns \"success\": true and \"data\": [{...}, ...]. Each element has its own \"success\" and \"data\" or \"error\" field.";

// G.TOOLREQLIXGETV.1
pub(crate) const GET_VERSION_DESC: &str = "Returns the version of the reqlix MCP server. \
Use this to check which version of the server is running. \
This tool has no parameters. \
Returns JSON with \"success\": true and \"data\": {\"version\": \"x.y.z\"}.";

// G.TOOLREQLIXD.1
pub(crate) const DELETE_REQUIREMENT_DESC: &str = "Deletes one or more existing requirements by index. \
The requirements will be permanently removed from the category file. \
Supports batch deletions with up to 100 indices. \
Single delete: Returns JSON with \"success\": true and \"data\": {...}. On error, returns \"success\": false. \
Batch delete: Returns \"success\": true and \"data\": [{...}, ...]. Each element has its own \"success\" and \"data\" or \"error\" field.";

// G.TOOLREQLIXS.1
pub(crate) const SEARCH_REQUIREMENTS_DESC: &str =
    "Searches for requirements by keywords across all categories. \
Accepts from 0 to 100 keywords. Each keyword max 200 characters. \
Returns all requirements where the title or text contains at least one of the specified keywords. \
Search is case-insensitive. \
Returns JSON with \"success\": true and \"data\": {\"keywords\": [...], \"results\": [...]}. \
If keywords array is empty, returns success with empty results array. \
On error, returns JSON with \"success\": false and \"error\": \"error message\".";
