// Main entry point for MCP server (G.G.3)
// All business logic is in lib.rs - this file only contains MCP server wrappers

use anyhow::Result;
use reqlix::RequirementsServer;
use reqlix::{
    GetInstructionsParams, GetCategoriesParams, GetChaptersParams, GetRequirementsParams,
    GetRequirementParams, InsertRequirementParams, UpdateRequirementParams, GetVersionParams,
    DeleteRequirementParams, SearchRequirementsParams, FuzzySearchRequirementsParams,
};
use rmcp::{
    model::{
        CallToolRequestParam, CallToolResult, Content, ListToolsResult, PaginatedRequestParam,
        ServerCapabilities, Tool,
    },
    service::RequestContext,
    service::RoleServer,
    transport::stdio,
    ServerHandler, ServiceExt,
};
use schemars::JsonSchema;
use std::borrow::Cow;
use std::env;

// =============================================================================
// Tool descriptions (T.R.1, T.REQLIXGETC.1, T.REQLIXGETCH.1, T.REQLIXGETR.1, T.REQLIXGETREQUIREMENT.1, T.REQLIXI.1, T.REQLIXU.1)
// =============================================================================

const GET_INSTRUCTIONS_DESC: &str = "CALL THIS BEFORE ANY CODE OPERATION (reading or writing). \
Returns instructions on how to work with requirements, including a MANDATORY workflow that MUST be followed for all code modifications. \
This MCP server is the single source of truth for everything related to requirements. \
Returns JSON with \"success\": true and \"data\": {\"content\": \"...\"} containing instructions with a mandatory workflow. \
On error, returns JSON with \"success\": false and \"error\": \"error message\".";

const GET_CATEGORIES_DESC: &str = "Returns a list of all available requirement categories. \
Use this to discover what categories exist before querying chapters or requirements. \
Returns JSON with \"success\": true and \"data\": {\"categories\": [...]} (alphabetically sorted). \
If no categories exist, returns empty array: \"categories\": []. \
On error, returns JSON with \"success\": false and \"error\": \"error message\".";

const GET_CHAPTERS_DESC: &str = "Returns a list of all chapters (level-1 headings) in the \
specified category file. Use this to discover what chapters exist in a category before querying requirements. \
Returns JSON with \"success\": true and \"data\": {\"category\": \"...\", \"chapters\": [...]}. \
If category has no chapters, returns empty array: \"chapters\": []. \
On error (category not found), returns JSON with \"success\": false and \"error\": \"error message\".";

const GET_REQUIREMENTS_DESC: &str = "Returns a list of all requirement titles (with indices) \
in the specified category and chapter. Use this to browse requirements in a chapter. \
To get full requirement content, use reqlix_get_requirement. \
Returns JSON with \"success\": true and \"data\": {\"category\": \"...\", \"chapter\": \"...\", \"requirements\": [{\"index\": \"...\", \"title\": \"...\"}, ...]}. \
If chapter has no requirements, returns empty array: \"requirements\": []. \
On error (category/chapter not found), returns JSON with \"success\": false and \"error\": \"error message\".";

// T.REQLIXGETREQUIREMENT.1
const GET_REQUIREMENT_DESC: &str = "Returns the full content (title and text) of one or more requirements by index. \
Index format: {CATEGORY}.{CHAPTER}.{NUMBER} (e.g., G.G.1, T.U.2). \
Supports batch requests with up to 100 indices. \
Single request: Returns JSON with \"success\": true and \"data\": {...}. On error, returns \"success\": false. \
Batch request: Returns \"success\": true and \"data\": [{...}, ...]. Each element has its own \"success\" and \"data\" or \"error\" field.";

const INSERT_REQUIREMENT_DESC: &str = "Inserts a new requirement into the specified category \
and chapter. The title must be generated by the LLM and provided as a parameter. \
The title must be a concise name that reflects the essence of the requirement. \
Category must contain only lowercase English letters (a-z) and underscore (_). \
Chapter must contain only uppercase and lowercase English letters (A-Z, a-z), spaces, colons (:), and hyphens (-). \
Returns JSON with \"success\": true and \"data\": {\"index\": \"...\", \"title\": \"...\", \"text\": \"...\", \"category\": \"...\", \"chapter\": \"...\"}. \
On error (title already exists, file system error, validation error), returns JSON with \"success\": false and \"error\": \"error message\".";

// T.REQLIXU.1
const UPDATE_REQUIREMENT_DESC: &str = "Updates one or more existing requirements by index with new text and optional new title. \
If title is provided, it must be unique within the chapter. If not provided, the existing title is kept. \
Supports batch updates with up to 100 requirements. \
Category must contain only lowercase English letters (a-z) and underscore (_). \
Chapter must contain only uppercase and lowercase English letters (A-Z, a-z), spaces, colons (:), and hyphens (-). \
Single update: Returns JSON with \"success\": true and \"data\": {...}. On error, returns \"success\": false. \
Batch update: Returns \"success\": true and \"data\": [{...}, ...]. Each element has its own \"success\" and \"data\" or \"error\" field.";

// T.REQLIXGETV.1
const GET_VERSION_DESC: &str = "Returns the version of the reqlix MCP server. \
Use this to check which version of the server is running. \
This tool has no parameters. \
Returns JSON with \"success\": true and \"data\": {\"version\": \"x.y.z\"}.";

// T.REQLIXD.1
// T.REQLIXD.1
const DELETE_REQUIREMENT_DESC: &str = "Deletes one or more existing requirements by index. \
The requirements will be permanently removed from the category file. \
Supports batch deletions with up to 100 indices. \
Single delete: Returns JSON with \"success\": true and \"data\": {...}. On error, returns \"success\": false. \
Batch delete: Returns \"success\": true and \"data\": [{...}, ...]. Each element has its own \"success\" and \"data\" or \"error\" field.";

// T.REQLIXS.1
const SEARCH_REQUIREMENTS_DESC: &str = "Searches for requirements by keywords across all categories. \
Accepts from 0 to 100 keywords. Each keyword max 200 characters. \
Returns all requirements where the title or text contains at least one of the specified keywords. \
Search is case-insensitive. \
Returns JSON with \"success\": true and \"data\": {\"keywords\": [...], \"results\": [...]}. \
If keywords array is empty, returns success with empty results array. \
On error, returns JSON with \"success\": false and \"error\": \"error message\".";

// T.REQLIXF.1
const FUZZY_SEARCH_REQUIREMENTS_DESC: &str = "Searches for requirements using semantic similarity (fuzzy search) across all categories. \
Uses embedding vectors to find requirements semantically similar to the query text. \
Returns requirements ordered by similarity score (most similar first). \
Accepts a query string (max 10000 characters) and optional limit parameter (default: 10, max: 1000). \
Returns JSON with \"success\": true and \"data\": {\"query\": \"...\", \"results\": [...]}. \
Each result includes a similarity score (0.0 to 1.0, higher is more similar). \
On error, returns JSON with \"success\": false and \"error\": \"error message\".";

// Constants and data structures are defined in lib.rs (G.G.3)

// Parameter types are imported from reqlix::params (G.G.3)

// =============================================================================
// MCP Server wrapper (G.G.3: All logic in lib.rs, only wrappers here)
// =============================================================================

/// MCP server wrapper that uses reqlix::RequirementsServer for all business logic (G.G.3)
/// All business logic methods have been removed - they delegate to lib.rs
#[derive(Debug, Clone, Default)]
struct McpServer;

impl McpServer {
    fn new() -> Self {
        Self
    }
}

// All business logic has been moved to lib.rs (G.G.3)
// The following methods were removed and now delegate to lib.rs:
// - All validation methods (validate_*)
// - All file system helpers (get_requirements_dir, find_or_create_requirements_file, etc.)
// - All parsing helpers (parse_level1_heading, parse_level2_heading, etc.)
// - All requirement helpers (read_requirements_streaming, find_requirement_streaming, etc.)
// - All insert/update helpers (get_or_calculate_category_prefix, etc.)
// - update_single_requirement, delete_single_requirement, get_single_requirement

// Helper function for building tool schemas (G.G.3: only MCP-specific code here)
fn build_tool_schema<T: JsonSchema>(name: &str, description: &'static str) -> Tool {
    let schema = schemars::schema_for!(T);
    let input_schema: serde_json::Value = serde_json::to_value(&schema).unwrap_or_default();

    Tool {
        name: name.to_string().into(),
        description: Some(Cow::Borrowed(description)),
        input_schema: serde_json::from_value(input_schema).unwrap_or_default(),
        annotations: None,
        icons: None,
        meta: None,
        output_schema: None,
        title: None,
    }
}

// =============================================================================
// ServerHandler implementation - delegates all business logic to lib.rs (G.G.3)
// =============================================================================

#[allow(clippy::manual_async_fn)]
impl ServerHandler for McpServer {
    fn get_info(&self) -> rmcp::model::ServerInfo {
        rmcp::model::ServerInfo {
            capabilities: ServerCapabilities::builder().enable_tools().build(),
            server_info: rmcp::model::Implementation {
                name: "reqlix".into(),
                version: env!("CARGO_PKG_VERSION").into(),
                title: None,
                icons: None,
                website_url: None,
            },
            ..Default::default()
        }
    }

    fn list_tools(
        &self,
        _request: Option<PaginatedRequestParam>,
        _context: RequestContext<RoleServer>,
    ) -> impl std::future::Future<
        Output = std::result::Result<ListToolsResult, rmcp::model::ErrorData>,
    > + Send
           + '_ {
        async move {
            let tools = vec![
                build_tool_schema::<GetInstructionsParams>(
                    "reqlix_get_instructions",
                    GET_INSTRUCTIONS_DESC,
                ),
                build_tool_schema::<GetCategoriesParams>(
                    "reqlix_get_categories",
                    GET_CATEGORIES_DESC,
                ),
                build_tool_schema::<GetChaptersParams>(
                    "reqlix_get_chapters",
                    GET_CHAPTERS_DESC,
                ),
                build_tool_schema::<GetRequirementsParams>(
                    "reqlix_get_requirements",
                    GET_REQUIREMENTS_DESC,
                ),
                build_tool_schema::<GetRequirementParams>(
                    "reqlix_get_requirement",
                    GET_REQUIREMENT_DESC,
                ),
                build_tool_schema::<InsertRequirementParams>(
                    "reqlix_insert_requirement",
                    INSERT_REQUIREMENT_DESC,
                ),
                build_tool_schema::<UpdateRequirementParams>(
                    "reqlix_update_requirement",
                    UPDATE_REQUIREMENT_DESC,
                ),
                build_tool_schema::<GetVersionParams>("reqlix_get_version", GET_VERSION_DESC),
                build_tool_schema::<DeleteRequirementParams>(
                    "reqlix_delete_requirement",
                    DELETE_REQUIREMENT_DESC,
                ),
                build_tool_schema::<SearchRequirementsParams>(
                    "reqlix_search_requirements",
                    SEARCH_REQUIREMENTS_DESC,
                ),
                build_tool_schema::<FuzzySearchRequirementsParams>(
                    "reqlix_fuzzy_search_requirements",
                    FUZZY_SEARCH_REQUIREMENTS_DESC,
                ),
            ];

            Ok(ListToolsResult {
                tools,
                next_cursor: None,
                meta: None,
            })
        }
    }

    fn call_tool(
        &self,
        request: CallToolRequestParam,
        _context: RequestContext<RoleServer>,
    ) -> impl std::future::Future<Output = std::result::Result<CallToolResult, rmcp::model::ErrorData>>
           + Send
           + '_ {
        async move {
            let result = match request.name.as_ref() {
                "reqlix_get_instructions" => {
                    let params: GetInstructionsParams =
                        serde_json::from_value(request.arguments.unwrap_or_default().into())
                            .map_err(|e| {
                                rmcp::model::ErrorData::invalid_params(e.to_string(), None)
                            })?;
                    RequirementsServer::handle_get_instructions(params)
                }
                "reqlix_get_categories" => {
                    let params: GetCategoriesParams =
                        serde_json::from_value(request.arguments.unwrap_or_default().into())
                            .map_err(|e| {
                                rmcp::model::ErrorData::invalid_params(e.to_string(), None)
                            })?;
                    RequirementsServer::handle_get_categories(params)
                }
                "reqlix_get_chapters" => {
                    let params: GetChaptersParams =
                        serde_json::from_value(request.arguments.unwrap_or_default().into())
                            .map_err(|e| {
                                rmcp::model::ErrorData::invalid_params(e.to_string(), None)
                            })?;
                    RequirementsServer::handle_get_chapters(params)
                }
                "reqlix_get_requirements" => {
                    let params: GetRequirementsParams =
                        serde_json::from_value(request.arguments.unwrap_or_default().into())
                            .map_err(|e| {
                                rmcp::model::ErrorData::invalid_params(e.to_string(), None)
                            })?;
                    RequirementsServer::handle_get_requirements(params)
                }
                "reqlix_get_requirement" => {
                    let params: GetRequirementParams =
                        serde_json::from_value(request.arguments.unwrap_or_default().into())
                            .map_err(|e| {
                                rmcp::model::ErrorData::invalid_params(e.to_string(), None)
                            })?;
                    RequirementsServer::handle_get_requirement(params)
                }
                "reqlix_insert_requirement" => {
                    let params: InsertRequirementParams =
                        serde_json::from_value(request.arguments.unwrap_or_default().into())
                            .map_err(|e| {
                                rmcp::model::ErrorData::invalid_params(e.to_string(), None)
                            })?;
                    RequirementsServer::handle_insert_requirement(params)
                }
                "reqlix_update_requirement" => {
                    let params: UpdateRequirementParams =
                        serde_json::from_value(request.arguments.unwrap_or_default().into())
                            .map_err(|e| {
                                rmcp::model::ErrorData::invalid_params(e.to_string(), None)
                            })?;
                    RequirementsServer::handle_update_requirement(params)
                }
                "reqlix_get_version" => {
                    // T.REQLIXGETV.3: No parameters required
                    let params: GetVersionParams =
                        serde_json::from_value(request.arguments.unwrap_or_default().into())
                            .map_err(|e| {
                                rmcp::model::ErrorData::invalid_params(e.to_string(), None)
                            })?;
                    RequirementsServer::handle_get_version(params)
                }
                "reqlix_delete_requirement" => {
                    // T.REQLIXD.2: Parse parameters
                    let params: DeleteRequirementParams =
                        serde_json::from_value(request.arguments.unwrap_or_default().into())
                            .map_err(|e| {
                                rmcp::model::ErrorData::invalid_params(e.to_string(), None)
                            })?;
                    RequirementsServer::handle_delete_requirement(params)
                }
                "reqlix_search_requirements" => {
                    // T.REQLIXS.2: Parse parameters
                    let params: SearchRequirementsParams =
                        serde_json::from_value(request.arguments.unwrap_or_default().into())
                            .map_err(|e| {
                                rmcp::model::ErrorData::invalid_params(e.to_string(), None)
                            })?;
                    RequirementsServer::handle_search_requirements(params)
                }
                "reqlix_fuzzy_search_requirements" => {
                    // T.REQLIXF.2: Parse parameters
                    let params: FuzzySearchRequirementsParams =
                        serde_json::from_value(request.arguments.unwrap_or_default().into())
                            .map_err(|e| {
                                rmcp::model::ErrorData::invalid_params(e.to_string(), None)
                            })?;
                    RequirementsServer::handle_fuzzy_search_requirements(params)
                }
                _ => {
                    return Err(rmcp::model::ErrorData::invalid_params(
                        format!("Unknown tool: {}", request.name),
                        None,
                    ));
                }
            };

            Ok(CallToolResult {
                content: vec![Content::text(result)],
                is_error: None,
                meta: None,
                structured_content: None,
            })
        }
    }
}

// =============================================================================
// Main entry point
// =============================================================================

#[tokio::main]
async fn main() -> Result<()> {
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::from_default_env()
                .add_directive(tracing::Level::INFO.into()),
        )
        .with_writer(std::io::stderr)
        .init();

    tracing::info!("Starting Reqlix MCP server");

    let service = McpServer::new();
    let server = service.serve(stdio()).await?;

    tracing::info!("Reqlix MCP server started successfully");

    server.waiting().await?;

    Ok(())
}
