// Parameter structures (G.REQLIX_GET_I.2, G.REQLIX_GET_CA.2, G.REQLIX_GET_CH.2, G.REQLIX_GET_REQUIREMENTS.2, G.REQLIX_GET_REQUIREMENT.2, G.REQLIX_I.2, G.REQLIX_U.2)

use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

/// Parameters for reqlix_get_instructions (G.REQLIX_GET_I.2)
#[derive(Debug, Serialize, Deserialize, JsonSchema)]
pub struct GetInstructionsParams {
    /// Path to the project root directory.
    pub project_root: String,
    /// Brief description of the operation that LLM intends to perform.
    pub operation_description: String,
}

/// Parameters for reqlix_get_categories (G.REQLIX_GET_CA.2)
#[derive(Debug, Serialize, Deserialize, JsonSchema)]
pub struct GetCategoriesParams {
    /// Path to the project root directory.
    pub project_root: String,
    /// Brief description of the operation that LLM intends to perform.
    pub operation_description: String,
}

/// Parameters for reqlix_get_chapters (G.REQLIX_GET_CH.2)
#[derive(Debug, Serialize, Deserialize, JsonSchema)]
pub struct GetChaptersParams {
    /// Path to the project root directory.
    pub project_root: String,
    /// Brief description of the operation that LLM intends to perform.
    pub operation_description: String,
    /// Category key (e.g., "general", "testing").
    pub category: String,
}

/// Parameters for reqlix_get_requirements (G.REQLIX_GET_REQUIREMENTS.2)
#[derive(Debug, Serialize, Deserialize, JsonSchema)]
pub struct GetRequirementsParams {
    /// Path to the project root directory.
    pub project_root: String,
    /// Brief description of the operation that LLM intends to perform.
    pub operation_description: String,
    /// Category key (e.g., "general", "testing").
    pub category: String,
    /// Chapter name (e.g., "General Requirements", "Unit Tests").
    pub chapter: String,
}

/// Index parameter that can be a single string or array of strings (G.REQLIX_GET_REQUIREMENT.2, G.TOOLREQLIXD.2)
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(untagged)]
pub enum IndexParam {
    /// Single index (e.g., "G.G.1")
    Single(String),
    /// Array of indices for batch operations (max 100)
    Batch(Vec<String>),
}

/// Parameters for reqlix_get_requirement (G.REQLIX_GET_REQUIREMENT.2)
#[derive(Debug, Serialize, Deserialize, JsonSchema)]
pub struct GetRequirementParams {
    /// Path to the project root directory.
    pub project_root: String,
    /// Brief description of the operation that LLM intends to perform.
    pub operation_description: String,
    /// Requirement index or array of indices (max 100). Example: "G.G.1" or ["G.G.1", "G.G.2", "T.U.1"].
    pub index: IndexParam,
}

/// Parameters for reqlix_insert_requirement (G.REQLIX_I.2)
#[derive(Debug, Serialize, Deserialize, JsonSchema)]
pub struct InsertRequirementParams {
    /// Path to the project root directory.
    pub project_root: String,
    /// Brief description of the operation that LLM intends to perform.
    pub operation_description: String,
    /// Category key (e.g., "general", "testing").
    pub category: String,
    /// Chapter name (e.g., "General Requirements", "Unit Tests").
    pub chapter: String,
    /// Requirement text (body content).
    pub text: String,
    /// Requirement title (required). A concise name that reflects the essence of the requirement.
    /// Must be generated by the LLM and be unique within the chapter.
    pub title: String,
}

/// Single update item for batch operations (G.REQLIX_U.2)
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
pub struct UpdateItem {
    /// Requirement index (e.g., "G.G.1", "T.U.2").
    pub index: String,
    /// New requirement text (body content).
    pub text: String,
    /// New requirement title (optional). If provided, must be unique within the chapter.
    pub title: Option<String>,
}

/// Parameters for reqlix_update_requirement (G.REQLIX_U.2)
/// Supports single update (index+text+title) or batch update (items array).
#[derive(Debug, Serialize, Deserialize, JsonSchema)]
pub struct UpdateRequirementParams {
    /// Path to the project root directory.
    pub project_root: String,
    /// Brief description of the operation that LLM intends to perform.
    pub operation_description: String,
    /// Requirement index for single update (e.g., "G.G.1", "T.U.2").
    /// Use either index+text+title for single update OR items for batch update.
    pub index: Option<String>,
    /// New requirement text for single update (body content).
    pub text: Option<String>,
    /// New requirement title for single update (optional).
    pub title: Option<String>,
    /// Array of update objects for batch update (max 100).
    /// Use either index+text+title for single update OR items for batch update.
    pub items: Option<Vec<UpdateItem>>,
}

/// Parameters for reqlix_get_version (G.TOOLREQLIXGETV.3 - no parameters)
#[derive(Debug, Serialize, Deserialize, JsonSchema)]
pub struct GetVersionParams {}

/// Parameters for reqlix_delete_requirement (G.TOOLREQLIXD.2)
#[derive(Debug, Serialize, Deserialize, JsonSchema)]
pub struct DeleteRequirementParams {
    /// Path to the project root directory.
    pub project_root: String,
    /// Brief description of the operation that LLM intends to perform.
    pub operation_description: String,
    /// Requirement index or array of indices to delete (max 100). Example: "G.G.1" or ["G.G.1", "G.G.2"].
    pub index: IndexParam,
}

/// Keywords parameter that can be a single string or array of strings (G.TOOLREQLIXS.2)
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
#[serde(untagged)]
pub enum KeywordsParam {
    /// Single keyword (e.g., "auth")
    Single(String),
    /// Array of keywords for search (max 100)
    Batch(Vec<String>),
}

/// Parameters for reqlix_search_requirements (G.TOOLREQLIXS.2)
#[derive(Debug, Serialize, Deserialize, JsonSchema)]
pub struct SearchRequirementsParams {
    /// Path to the project root directory.
    pub project_root: String,
    /// Brief description of the operation that LLM intends to perform.
    pub operation_description: String,
    /// Single keyword (max 200 characters) or array of keywords (0 to 100 elements, each max 200 characters).
    /// Example: "auth" or ["auth", "user", "login"].
    pub keywords: KeywordsParam,
}
